name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths: ['src/**/*', '.github/workflows/ci.yml' ]
  push:
    branches: [ master ]
    paths: ['src/**/*', '.github/workflows/ci.yml' ]

jobs:
  build_console:
    runs-on: windows-latest
    env:
      RID: win-x64
      SLN_PATH: src/RdpProtocolHandler.sln
      CSPROJ_PATH: src/RdpProtocolHandler/RdpProtocolHandler.csproj
      BUILD_CONFIGURATION: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate version number with date and workflow Run Number
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = "$buildDay.${{ github.RUN_NUMBER }}.0"

        echo "app_ver_output=$ver" >> $GITHUB_OUTPUT
        echo "app_ver_var=$ver" >> $GITHUB_ENV
        echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT

    - name: Use the value
      id: step_two
      run: |
        echo "old style run_number: $env:GITHUB_RUN_NUMBER"
        echo "new style run_number: ${{ github.RUN_NUMBER }}"
        
        echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
        echo "app_ver_var: ${{ env.app_ver_var }}"
        echo "app_ver_output: ${{ steps.version-creator.outputs.app_ver_output }}"

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
   
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.CSPROJ_PATH }} --runtime ${{ env.RID }}

    - name: Restore
      run: msbuild ${{ env.CSPROJ_PATH }} /t:Restore /p:Configuration=${{ env.BUILD_CONFIGURATION }}

    - name: Build
      run: msbuild ${{ env.CSPROJ_PATH }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:RuntimeIdentifier=${{ env.RID }}

    - uses: actions/upload-artifact@v3
      with:
        name: app
        path: src/RdpProtocolHandler/bin/Release