name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths: ['src/**/*', '.github/workflows/ci.yml' ]
  push:
    branches: [ main ]
    paths: ['src/**/*', '.github/workflows/ci.yml' ]

jobs:
  build_console:
    runs-on: windows-latest
    env:
      RID: win-x64
      SLN_PATH: src/RdpProtocolHandler.sln
      CSPROJ_PATH: src/RdpProtocolHandler/RdpProtocolHandler.csproj
      BUILD_CONFIGURATION: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore
      run: msbuild ${{ env.SLN_PATH }} /t:Restore /p:Configuration=${{ env.BUILD_CONFIGURATION }}
      
    - name: Build
      run: msbuild ${{ env.SLN_PATH }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:RuntimeIdentifier=${{ env.RID }}

    - uses: actions/upload-artifact@v3
      with:
        name: app
        path: src/RdpProtocolHandler/bin/Release